name: model-harmonics
channels:
  - conda-forge
dependencies:
  - boto3
  - cartopy
  - cdsapi
  - ecmwf-api-client
  - h5py
  - fiona
  - future
  - lxml
  - matplotlib
  - netCDF4
  - notebook
  - numpy
  - pyproj
  - python>=3.6
  - python-dateutil
  - pyyaml
  - shapely
  - scikit-learn
  - scipy
  - pip
  - pip:
     - git+https://github.com/tsutterley/geoid-toolkit.git
     - git+https://github.com/tsutterley/read-GRACE-geocenter.git
     - git+https://github.com/tsutterley/read-GRACE-harmonics.git
