name: model-harmonics
channels:
  - conda-forge
dependencies:
  - python>=3.6
  - notebook
  - cdsapi
  - ecmwf-api-client
  - fiona
  - pyproj
  - shapely
  - pip
  - pip:
     - git+https://github.com/tsutterley/read-GRACE-harmonics.git
