name: model-docs
channels:
  - conda-forge
dependencies:
  - boto3
  - cdsapi
  - docutils<0.18
  - ecmwf-api-client
  - fiona
  - fontconfig
  - freetype
  - future
  - geos
  - graphviz
  - h5py
  - lxml
  - markupsafe==2.0.1
  - netCDF4
  - notebook
  - numpy
  - numpydoc
  - pip
  - proj>=8.0
  - pyproj
  - python>=3.6
  - python-dateutil
  - pyyaml
  - scikit-learn
  - scipy
  - shapely
  - sphinx
  - sphinx-argparse
  - sphinx_rtd_theme
  - texlive-core
  - pip:
     - git+https://github.com/tsutterley/read-GRACE-geocenter.git
     - git+https://github.com/tsutterley/geoid-toolkit.git
     - git+https://github.com/tsutterley/read-GRACE-harmonics.git
     - ..

